site_name: CUIT ICEC Wiki

# Repository
repo_name: 'cuit_icec/icec_wiki'
repo_url: 'https://github.com/cuit-icec/cuit-icec.github.io'
edit_uri: 'https://github.com/cuit-icec/cuit-icec.github.io/edit/main/docs/'

nav:
  - 简介:
    - Home: index.md
    - 如何参与 Wiki 的贡献: icec/contri.md
    - 成员: icec/members.md
    - 比赛以及作品: icec/competition.md
    - 资源:
      - 引导: icec/resource/intro.md
      - 软件安装包: icec/resource/soft.md 
      - 数据手册: icec/resource/datasheet.md
    - 相册: 
      - 引导: icec/photo/intro.md
      - 集体合照: icec/photo/together.md
      - 历年电赛: icec/photo/ticomp.md
    - 视频: icec/video.md
    # - About: about.md
  - 学习路线:
    - 对大一新生的指路: study_route/to_fresh.md
    - 进入电协后的指路:
      - 进入电协后基本要求: study_route/after_in.md
      - 硬件方向具体要求: study_route/hard.md
      - 软件方向具体要求: study_route/soft.md
  - 工具:
    - 引导: tool/intro.md
    - 编程:
      - 编辑器: 
        - Visual Studio Code: tool/software/code_editor/visual_studio_code.md
      - 构建工具:
        - Make: tool/software/construction_tool/make.md
    - 笔记:
      - 笔记相关的工具: tool/note/intro.md
      - Markdown: 
        - 介绍: tool/note/markdown/intro.md
        - Picgo: tool/note/markdown/picgo.md
        - Typora: tool/note/markdown/typora.md
        - 图床方案: tool/note/markdown/markdown_picbed.md
  - 编程基础:
    - 认识编程: programming/intro.md
    - 语言:
      - 认识语言: programming/language/intro.md
      - C: programming/language/c.md
      - C++: programming/language/cpp.md
      - Python: programming/language/python.md
    - 设计思想:
      - 认识设计思想: programming/design_thougt/intro.md
    - 系统:
      - 认识系统: programming/system/intro.md
  - 硬件基础: 
    - 模数电知识: hardware/elec.md
    - 仿真软件的使用: hardware/simu.md
    - 焊接技术: hardware/solder.md
    - PCB绘制: hardware/drawpcb.md
    - 各类元器件: hardware/component.md
    - 仪器使用: hardware/device.md
    - 阅读数据手册: hardware/datasheet.md
  - FPGA:
    - 引导: fpga/intro.md
  - MCU:
    - C51: mcu/c51.md
    - STM32: mcu/stm32.md
    - MSP432: mcu/msp432.md
    - ESP32: mcu/esp32.md
    - Node MCU: mcu/node_mcu.md
    - Arduino: mcu/arduino.md  
  - 通讯协议:
    - ONEWIRE: protocol/onewire.md
    - IIC: protocol/iic.md
    - IIS: protocol/iis.md
    - SPI: protocol/spi.md
    - CAN: protocol/can.md
    - UART: protocol/uart.md
    - USB: protocol/usb.md
  - 模块/芯片:
    - 传感器: module/sensor.md
    - 显示  : module/display.md
    - 无线: module/wireless.md
    - 存储: module/storage.md
  - 专业技术领域: 
    - 引导: pro/intro.md

theme:
  name: 'material'
  language: 'zh'
  include_search_page: false
  search_index_only: true
  features:
    - tabs
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  icon:
    logo: material/book

copyright: 'Copyright &copy; 2020 CUIT ICEC'
site_author: ICEC

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js'
  - '_static/js/extra.js?v=1'

extra_css:
  - 'https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css'

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
      
  - pymdownx.superfences
  - pymdownx.details
